name: build
on: [push, pull_request]
jobs:
  run-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Run specs
        run: docker-compose run graphql rails test