name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build App
        run: docker-compose build
      - name: Run app
        run: docker-compose up